#pragma once
// Stub - real values come from SCREEN_WIDTH/SCREEN_HEIGHT defines
#ifndef SCREEN_WIDTH
#define SCREEN_WIDTH 480
#endif
#ifndef SCREEN_HEIGHT  
#define SCREEN_HEIGHT 480
#endif
// Launcher layout
#define LAUNCHER_COLS 4
#define LAUNCHER_ROWS_PAGE1 2
#define LAUNCHER_ROWS_OTHER 4
#define LAUNCHER_CELL_WIDTH 110
#define LAUNCHER_CELL_HEIGHT 110
#define LAUNCHER_CELL_HEIGHT_P1 110
#define LAUNCHER_PAGE_WIDTH SCREEN_WIDTH
#define LAUNCHER_PAGE_HEIGHT SCREEN_HEIGHT
#define CLOCK_TOP_OFFSET 20
#define DATE_TOP_OFFSET 90
#define ICONS_START_Y_PAGE1 150
#define ICONS_START_Y_OTHER 70
#define LAUNCHER_LABEL_TOP_OFFSET 70
#define LAUNCHER_LETTER_TOP_OFFSET 10
#define DOT_SIZE 8
#define DOT_SPACING 8
#define DOTS_BOTTOM_OFFSET 20
#define LAUNCHER_SHOW_DOTS_PAGE1 false
#define LAUNCHER_SHOW_COMPACT_CLOCK true
#define LAUNCHER_TITLE_MAX_CHARS 10

// Scaling macros
#define SCALED(x) ((x) * SCREEN_WIDTH / 480)
#define SCALED_H(x) ((x) * SCREEN_HEIGHT / 480)
