#!/usr/bin/env python3
"""
TelaOS Project Compiler (mock build)
Usage: python3 build.py <path_to_project> [--rebuild] [--mock]
       python3 build.py /path/to/TelaOS --mock
       python3 build.py /path/to/TelaOS --mock --rebuild
"""

import subprocess
import sys
from pathlib import Path

# Paths
COMPILER_DIR = Path(__file__).parent
STUBS_DIR = COMPILER_DIR / "stubs"
BUILD_DIR = COMPILER_DIR / "build"

CXX = "g++"
STD = "gnu++2a"

DEFINES = [
    "SCREEN_WIDTH=480",
    "SCREEN_HEIGHT=480",
    "BOARD_TWATCH_2020",
]

def find_all_sources(src_dir: Path):
    """Find all .cpp/.c files in src/, excluding font/"""
    sources = []
    for pattern in ("*.cpp", "*.c"):
        for cpp in src_dir.rglob(pattern):
            if "font" not in cpp.parts:
                sources.append(cpp)
    return sorted(sources)

def get_obj_path(src: Path, src_dir: Path, build_dir: Path) -> Path:
    """Get .o path for source file"""
    try:
        rel = src.relative_to(src_dir)
    except ValueError:
        # Source outside src_dir (e.g. lib/blowfish/bf_blowfish.c)
        rel = Path("lib") / src.name
    return build_dir / rel.with_suffix('.o')

def needs_rebuild(src: Path, obj: Path, force: bool = False) -> bool:
    if force:
        return True
    if not obj.exists():
        return True
    obj_mtime = obj.stat().st_mtime
    # Rebuild if source changed
    if src.stat().st_mtime > obj_mtime:
        return True
    # Check .d dependency file (generated by -MMD)
    dep = obj.with_suffix('.d')
    if not dep.exists():
        return True  # no deps recorded — must rebuild
    deps = parse_depfile(dep)
    for d in deps:
        p = Path(d)
        if not p.exists():
            return True  # header removed — rebuild
        if p.stat().st_mtime > obj_mtime:
            return True  # header changed — rebuild
    return False

def parse_depfile(dep: Path) -> list:
    """Parse GCC .d file → list of dependency paths (headers)."""
    text = dep.read_text()
    # Format: "obj.o: src.cpp header1.h header2.h \\\n  header3.h ..."
    # Join continuation lines, split on whitespace, skip target + source
    text = text.replace('\\\n', ' ')
    parts = text.split()
    # Skip "target.o:" and the source .cpp (first two tokens)
    if len(parts) > 2 and parts[0].endswith(':'):
        return parts[2:]  # everything after "obj.o: src.cpp"
    return []

def compile_one(src: Path, obj: Path, includes: list, defines: list) -> tuple:
    obj.parent.mkdir(parents=True, exist_ok=True)

    is_c = src.suffix == ".c"
    if is_c:
        cmd = ["gcc", "-std=gnu11", "-MMD", "-c", "-o", str(obj)]
    else:
        cmd = [CXX, f"-std={STD}", "-MMD", "-include", "cstring", "-c", "-o", str(obj)]
    cmd += [f"-D{d}" for d in defines]
    cmd += [f"-I{inc}" for inc in includes]
    cmd.append(str(src))

    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode == 0, result.stdout + result.stderr

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 build.py <path_to_project> [--rebuild]")
        print("Example: python3 build.py /path/to/TelaOS --mock")
        print("         python3 build.py /path/to/TelaOS --mock --rebuild")
        return 1
    
    project_dir = Path(sys.argv[1]).resolve()
    force_rebuild = "--rebuild" in sys.argv
    mock_enabled = "--mock" in sys.argv
    
    src_dir = project_dir / "src"
    include_dir = project_dir / "include"
    
    if not src_dir.exists():
        print(f"ERROR: Source directory not found: {src_dir}")
        return 1
    
    # Add mock define if requested
    defines = DEFINES.copy()
    if mock_enabled:
        defines.append("LVGL_MOCK_ENABLED")
    
    # Include order: real Lua first, then stubs (LVGL etc.), then project, then libs
    lua_include = COMPILER_DIR / "lib" / "lua54" / "include"
    if not lua_include.exists():
        print(f"ERROR: Lua headers not found: {lua_include}")
        print(f"Run: ./lib/build_libs.sh")
        return 1

    includes = [
        str(lua_include),
        str(STUBS_DIR),
        str(src_dir),
        str(include_dir),
        str(COMPILER_DIR / "lib" / "ckdl" / "include"),
        str(COMPILER_DIR / "lib" / "ckdl" / "bindings" / "cpp" / "include"),
    ]
    
    # Add project lib includes (small vendored third-party components)
    LIB_COMPONENTS = ["blowfish"]  # add new ones here
    lib_dir = project_dir / "lib"
    for name in LIB_COMPONENTS:
        comp = lib_dir / name
        if comp.exists():
            includes.append(str(comp))
    
    # Use separate build directory for mock builds
    build_dir = BUILD_DIR / "mock" if mock_enabled else BUILD_DIR
    build_dir.mkdir(parents=True, exist_ok=True)
    
    sources = find_all_sources(src_dir)
    
    # Add third-party lib sources (small vendored components only)
    LIB_COMPONENTS = ["blowfish"]  # add new ones here
    lib_dir = project_dir / "lib"
    for name in LIB_COMPONENTS:
        comp = lib_dir / name
        if comp.exists():
            for pattern in ("*.cpp", "*.c"):
                for f in comp.glob(pattern):
                    sources.append(f)
    
    # Group by folder
    folders = {}
    for src in sources:
        try:
            parts = src.relative_to(src_dir).parts
            folder = parts[0] if len(parts) > 1 else "."
        except ValueError:
            folder = "lib"
        folders.setdefault(folder, []).append(src)
    
    print(f"Project: {project_dir}")
    print(f"Found {len(sources)} .cpp files in {len(folders)} folders")
    if force_rebuild:
        print("Mode: --rebuild (force all)")
    if mock_enabled:
        print("Mode: --mock (LVGL_MOCK_ENABLED)")
        print(f"Build dir: {build_dir}")
    
    # Check what needs rebuild (uses .d dependency files from -MMD)
    to_build = []
    for src in sources:
        obj = get_obj_path(src, src_dir, build_dir)
        if needs_rebuild(src, obj, force_rebuild):
            to_build.append((src, obj))
    
    if not to_build:
        print("✓ All files up to date!")
        return 0
    
    print(f"Compiling {len(to_build)} files...\n")
    
    errors = []
    for i, (src, obj) in enumerate(to_build, 1):
        try:
            rel = src.relative_to(src_dir)
        except ValueError:
            rel = Path("lib") / src.name
        ok, output = compile_one(src, obj, includes, defines)
        
        if ok:
            print(f"[{i}/{len(to_build)}] ✓ {rel}")
        else:
            print(f"[{i}/{len(to_build)}] ✗ {rel}")
            errors.append((rel, output))
    
    print()
    if errors:
        print(f"✗ {len(errors)} file(s) failed:\n")
        for rel, output in errors[:3]:
            print(f"--- {rel} ---")
            print(output[:2000])
        if len(errors) > 3:
            print(f"\n... and {len(errors) - 3} more")
        return 1
    else:
        print(f"✓ All {len(to_build)} files compiled successfully!")
        return 0

if __name__ == "__main__":
    sys.exit(main())
