// === AUTO-GENERATED FILE - DO NOT EDIT! ===
// SCRIPT_VERSION: 1.0
// Generated by scripts/embed_system_icons.py
//
// This is a placeholder. Run the script to generate actual icons:
//   python scripts/embed_system_icons.py

#pragma once
#include <lvgl.h>

#ifdef USE_BUILTIN_ICONS

// No system icons embedded yet.
// Add PNG files to data/system/resources/icons/ and run the script.

/// Find system icon by name (e.g., "puzzle-game" or "tool")
static inline const lv_image_dsc_t* findSystemIcon(const char* name) {
    (void)name;
    return nullptr;
}

#else

static inline const lv_image_dsc_t* findSystemIcon(const char*) { return nullptr; }

#endif // USE_BUILTIN_ICONS
