#pragma once
/**
 * UI Layout - Adaptive layout for different screen sizes
 * 
 * Reference resolution: 480x480
 * Small screen threshold: 240px (compact layout, no dots on page 1)
 */

#include "hal/display_hal.h"  // for SCREEN_WIDTH, SCREEN_HEIGHT

// ============================================
// Scale macros
// ============================================
#define UI_SCALE_REF        480
#define SCALED(x)           ((x) * SCREEN_WIDTH / UI_SCALE_REF)
#define SCALED_H(x)         ((x) * SCREEN_HEIGHT / UI_SCALE_REF)

// ============================================
// Percentage macros - calculate pixels directly
// Use instead of lv_pct() for predictable behavior
// ============================================
#define PCT_W(x)            ((x) * SCREEN_WIDTH / 100)
#define PCT_H(x)            ((x) * SCREEN_HEIGHT / 100)
#define PCT(x)              PCT_W(x)  // Default to width (most common)

// ============================================
// Screen size thresholds
// ============================================
#define SMALL_SCREEN_THRESHOLD   280   // 240px screens and below
#define IS_SMALL_SCREEN          (SCREEN_HEIGHT < SMALL_SCREEN_THRESHOLD)

// ============================================
// Feature flags (define in platformio.ini)
// ============================================
// -DUSE_BUILTIN_ICONS   : Use pre-compiled icons from flash (generated by scripts/create_embedded_icons.py)
// -DNO_PNG_ICONS        : Disable PNG loading from filesystem/PSRAM (auto-enables USE_BUILTIN_ICONS)
// -DNO_BLE              : Disable Bluetooth
//
// Recommended configs:
//   ESP32 with PSRAM:  (no flags) - full functionality
//   ESP32 no PSRAM:    -DNO_PNG_ICONS
//   Old chips (T-Watch): -DNO_PNG_ICONS -DNO_BLE

// Auto-enable builtin icons when PNG is disabled
#if defined(NO_PNG_ICONS) && !defined(USE_BUILTIN_ICONS)
    #define USE_BUILTIN_ICONS
#endif

// ============================================
// Launcher layout constants
// ============================================
#define LAUNCHER_COLS            3
#define LAUNCHER_ROWS_PAGE1      2
#define LAUNCHER_ROWS_OTHER      3

#if IS_SMALL_SCREEN
    // Small screen: FIXED sizes to fit 240px
    #define LAUNCHER_CELL_WIDTH      (SCREEN_WIDTH / 3)   // 80px for 240
    #define LAUNCHER_CELL_HEIGHT_P1  70                   // Fits 48px icon + 16px label
    #define LAUNCHER_CELL_HEIGHT     72                   // Slightly more for other pages
    #define LAUNCHER_PAGE_WIDTH      SCREEN_WIDTH
    #define LAUNCHER_PAGE_HEIGHT     SCREEN_HEIGHT
#else
    // Normal screen: scaled from 480px reference
    #define LAUNCHER_CELL_WIDTH      SCALED(140)
    #define LAUNCHER_CELL_HEIGHT_P1  SCALED_H(110)
    #define LAUNCHER_CELL_HEIGHT     SCALED_H(115)
    #define LAUNCHER_PAGE_WIDTH      SCALED(466)
    #define LAUNCHER_PAGE_HEIGHT     SCALED_H(450)
#endif

// ============================================
// Clock positions - adaptive for small screens
// ============================================
#if IS_SMALL_SCREEN
    // Small screen: FIXED values, compact top layout
    // Clock 72px height, Date 16px
    #define CLOCK_TOP_OFFSET         0        // No top margin
    #define DATE_TOP_OFFSET          74       // Just below clock (72+2)
    #define ICONS_START_Y_PAGE1      100      // Visual gap from clock group
#else
    // Normal screen - scaled positions work fine
    #define CLOCK_TOP_OFFSET         SCALED_H(55)
    #define DATE_TOP_OFFSET          SCALED_H(140)
    #define ICONS_START_Y_PAGE1      SCALED_H(215)
#endif

// Icons start Y for pages 2+ (no clock on small screens)
#if IS_SMALL_SCREEN
    #define ICONS_START_Y_OTHER          5        // Start near top
    #define LAUNCHER_SHOW_COMPACT_CLOCK  false
    #define LAUNCHER_SHOW_DOTS_PAGE1     false    // Hide dots on page 1 to save space
#else
    #define ICONS_START_Y_OTHER          SCALED_H(95)
    #define LAUNCHER_SHOW_COMPACT_CLOCK  true
    #define LAUNCHER_SHOW_DOTS_PAGE1     true
#endif

// ============================================
// Icon and label layout
// ============================================
#if IS_SMALL_SCREEN
    #define LAUNCHER_ICON_SIZE           48              // Icons are 48x48
    #define LAUNCHER_LABEL_TOP_OFFSET    48              // Right below 48px icon
    #define LAUNCHER_LETTER_TOP_OFFSET   0               // Letter at top
    #define LAUNCHER_TITLE_MAX_CHARS     9               // Truncate long titles: "Calculat.."
#else
    #define LAUNCHER_ICON_SIZE           SCALED(64)
    #define LAUNCHER_LABEL_TOP_OFFSET    71              // 64px icon + 7px gap (original value)
    #define LAUNCHER_LETTER_TOP_OFFSET   SCALED_H(5)
    // No LAUNCHER_TITLE_MAX_CHARS — full titles on big screens
#endif

// ============================================  
// Dots (page indicator)
// ============================================
#if IS_SMALL_SCREEN
    #define DOT_SIZE                 6
    #define DOT_SPACING              4
    #define DOTS_BOTTOM_OFFSET       8
#else
    #define DOT_SIZE                 SCALED(10)
    #define DOT_SPACING              SCALED(8)
    #define DOTS_BOTTOM_OFFSET       SCALED_H(20)
#endif